services:
  postgres:
    container_name: 'memorize_db'
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=memorize'
      - 'POSTGRES_PASSWORD=mywords'
      - 'POSTGRES_USER=memorize'
    ports:
      - '5432'
