spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/memorize
    username: postgres
    password: admin
server:
  port: 8888
  error:
    include-stacktrace: ON_PARAM
    include-message: ALWAYS
