spring:
  datasource:
    url: jdbc:postgresql://localhost:35437/memorize
    username: memorize
    password: mywords
server:
  port: 8888
  error:
    include-stacktrace: ON_PARAM
    include-message: ALWAYS
